name: RxDropDown

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Cocoapods
      run: gem install cocoapods
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
    - name: Deploy Cocoapods
      run : |
        set -eo pipefail
        pod lib lint --allow-warnings
    - name: Deploy SPM
      run : swift package generate-xcodepoj
